### ISSUE TITLE
Fresh Install Error

### ISSUE THREAD

**Issue by fishmad** [trafik8787/lara-crud#1]
```
ErrorException (E_ERROR)
Invalid argument supplied for foreach() (View: C:\laragon\www\laravelapp\vendor\trafik8787\lara-crud\resources\views\common\app.blade.php) (View: C:\laragon\www\laravelapp\vendor\trafik8787\lara-crud\resources\views\common\app.blade.php)
```

`foreach ($this->admin->defaultUrlArr as $nodeClass => $item) {`

**Comment by trafik8787** [comment]
The error will be fixed thanks

**Comment by fishmad** [comment]
After install, I went http://localhost/admin.

PHP 7.1.13
```
    "require": {
        "php": ">=7.0.0",
        "fideloper/proxy": "~3.3",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0",
        "trafik8787/lara-crud": "^1.2"
```

**Comment by fishmad** [comment]
Sorry I just added App\Providers\LaraCrudProvider::class, in the config.app and it started working,
I thought auto discover had already picked it up during install but it had not.

It is now loading without error.

**Comment by fishmad** [comment]
AdminLTE script is not published in public/vender/lara-crud/js/ folder but is referenced in the output html,on/off canvas is not working as a result. <script src="http://localhost/vendor/lara-crud/js/adminlte.min.js"></script>

![image](https://user-images.githubusercontent.com/12012101/35489019-60516c7c-04e5-11e8-872c-caaf23d89124.png)

**Comment by fishmad** [comment]
Actually a lot mor JS file are not avaialve in the package or published.

![image](https://user-images.githubusercontent.com/12012101/35489203-c7f700ce-04e7-11e8-9987-30166d614058.png)

This is all I see once loaded.
![image](https://user-images.githubusercontent.com/12012101/35489209-dc209592-04e7-11e8-996f-5d860136b1e4.png)

**Comment by trafik8787** [comment]
With the loading of scripts, I will fix the problem. All is displayed correctly this is the main one where you can place your widgets. When you move to Article, you will see an example of the table that should have loaded during the installation.

**Comment by trafik8787** [comment]
Upgrade to v1.2.4
